# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
matrix:
  include:
    - python: 3.7
      env:
        - TESTMODE=full
        - COVERAGE=--coverage
    - python: 3.6
      env:
        - TESTMODE=fast
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - ccache
cache:
  directories:
    - $HOME/.ccache
before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - travis_retry pip install numpy
  - travis_retry pip install nose argparse
  - python -V
  - popd
script:
  - python $OPTIMIZE runtests.py -g -m $TESTMODE $COVERAGE
notifications:
  # Perhaps we should have status emails sent to the mailing list, but
  # let's wait to see what people think before turning that on.
  email: false
